### PR TITLE
Add times inline class

### PR DESCRIPTION
**Pull request by soywiz**
This will replace PlaybackTimes on KorAU: https://github.com/korlibs/korau/blob/a7f027a8be3e6f1c5093c1c7f37e18e61d057828/korau/src/commonMain/kotlin/com/soywiz/korau/sound/NativeSound.kt#L268-L280

### CODE REVIEW

**Comment by RezMike** [comment]
It looks well, but there's lacking of usage example for me.

**Comment by soywiz** [comment]
In KorAU it was used to define how much times to play an audio or a song. Infinite times, 1 time, 3 times, etc. Since that was KorAU I called that class `PlaybackTimes`, but since that's somehow related to an abstract time concept, I guessed we could move it here. I given a thought about if this would fit better in another library, but couldn't find other where this makes sense.

**Comment by RezMike** [comment]
Well, the use case is good. But the name of the class `Times` may be a bit confusing, because it has nothing in common with `Time`. Maybe we can rename the class to something like `NumberOfTimes`?

**Comment by soywiz** [comment]
I have renamed it to `NumberOfTimes`. Though a bit long. `NTimes` could be another option with a small explanation, but maybe not as clear.

**Pull request merged**
