### PR TITLE
TimesPerSecond / Hertz

### PR DESCRIPTION
**Pull request by soywiz**

### CODE REVIEW

**Comment by RezMike** [comment]
Maybe we should name the class `Frequency'? I'm not sure about specific use cases for the class and methods, I need to see usage examples.

**Comment by RezMike** [comment]
Also `100.milliseconds.hz` is confusing.

**Comment by soywiz** [comment]
I was thinking to use it in KorGE, though was not sure about its utility:

https://github.com/korlibs/korge/blob/0061506fabaa1b201c4c1def56519defc6b8c0ec/korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt#L1050

Was thinking about:
```
addFixedUpdater(10.timesPerSecond) {
}
```

**Comment by soywiz** [comment]
And yes, `Frequency` would be a better name for this indeed

**Comment by RezMike** [comment]
Well, `10.timesPerSecond` is quite good naming. But the resulting object should be of type `Frequency`.

It's a good use case, btw:
`addFixedUpdater(10.timesPerSecond) { ... }`
I think it fits here.

But we need to think about the ability of translating `TimeSpan` to `Frequency` and vice versa.

**Comment by RezMike** [comment]
Maybe instead of `100.milliseconds.hz` we can make something like `100.milliseconds.toFrequency()` or `Frequency.from(100.milliseconds)`

**Pull request merged**
