### PR TITLE
add DATETIME_UTC_COMPLETE and DATETIME_UTC_COMPLETE_FRACTION

### LINKED ISSUE #139: ISO8601.DATETIME_UTC_COMPLETE
Can we get a constant for the ISO8601-Instant-String (e.g. `2020-08-20T08:17:56Z`). There's already `ISO8601.DATETIME_COMPLETE` which comes close but is missing the `Z` at the end. And there is also no constant with the fraction-variant (e.g. `2020-08-20T08:17:56.123Z`).

I've added the following extensions to my project which would nicely fit into the library itself:

```kotlin
val DATETIME_UTC_COMPLETE = ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmssZ", "YYYY-MM-DDThh:mm:ssZ")
val DATETIME_UTC_COMPLETE_FRACTION = ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmss.sssZ", "YYYY-MM-DDThh:mm:ss.sssZ")
```

Or am I missing some constants? I've found `DateFormat.FORMAT2` which is the same but not for UTC. I'd be happy to add a PR as well if this is approved.

### PR DESCRIPTION
**Pull request by hardysim**
closes #139

### CODE REVIEW

**Comment by soywiz** [comment]
Can you add a test using those constants with valid dates?

**Comment by hardysim** [comment]
@soywiz maybe you can help me with the tests. I'm copying `testDateTimeComplete()` and adding basically adding `Z` to the the time-strings. This works fine for `format()` but not for `parse()`.

Here's the code:

```kotlin
@Test
    fun testDateTimeUtcComplete() {
        assertEquals("20190917T114805Z", ISO8601.DATETIME_UTC_COMPLETE.basic.format(1568720885000))
        assertEquals("2019-09-17T11:48:05Z", ISO8601.DATETIME_UTC_COMPLETE.extended.format(1568720885000))

        assertEquals("Tue, 17 Sep 2019 11:48:05 UTC", ISO8601.DATETIME_UTC_COMPLETE.parse("20190917T114805Z").utc.toString())
        assertEquals("Tue, 17 Sep 2019 11:48:05 UTC", ISO8601.DATETIME_UTC_COMPLETE.parse("2019-09-17T11:48:05Z").utc.toString())
    }

    @Test
    fun testDateTimeUtcCompleteFraction() {
        assertEquals("20190917T114805.000Z", ISO8601.DATETIME_UTC_COMPLETE_FRACTION.basic.format(1568720885000))
        assertEquals("2019-09-17T11:48:05.000Z", ISO8601.DATETIME_UTC_COMPLETE_FRACTION.extended.format(1568720885000))

        assertEquals("Tue, 17 Sep 2019 11:48:05 UTC", ISO8601.DATETIME_UTC_COMPLETE_FRACTION.parse("20190917T114805.000Z").utc.toString())
        assertEquals("Tue, 17 Sep 2019 11:48:05 UTC", ISO8601.DATETIME_UTC_COMPLETE_FRACTION.parse("2019-09-17T11:48:05.000Z").utc.toString())
    }
```

I get the error `Invalid format 20190917T114805Z` but I'm not sure how to fix that. How is `parse()` related to the `IsoDateTimeFormat` I'm defining?

**Comment by soywiz** [comment]
Sure. Please, commit the tests and I'll check it

**Comment by hardysim** [comment]
Done. Please have a look.

**Comment by soywiz** [comment]
Hey @hardysim thanks for your patience. I have finally looked at the issue, and it was related to timezone not being parsed on the ISO8601 parser. Since this is a PR I cannot add commits there so I have created a separated PR.

**Comment by soywiz** [comment]
Just merged https://github.com/korlibs/klock/pull/141 . Thanks for your contribution!

**Comment by hardysim** [comment]
@soywiz is there an ETA of a new release including this?

**Comment by soywiz** [comment]
Just triggered a build: https://github.com/korlibs/klock/actions/runs/264987210

**Comment by hardysim** [comment]
Perfect. It's included in 1.12.1

Maybe you want to update the changelog as well. It seems it hasn't been synced to new tags some time now.

**Pull request closed without merging**
